services:
  - type: web
    name: retete-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: REPLICATE_API_TOKEN
        fromDotEnv: true
      - key: WEBHOOK_HOST
        fromDotEnv: true