services:
  - type: web
    name: replicate-image-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token_here
      - key: REPLICATE_API_TOKEN
        value: your_replicate_api_token_here
      - key: WEBHOOK_URL
        value: https://your_render_domain.onrender.com